### ISSUE TITLE
Finalizing frontend design UI/UX

### ISSUE THREAD

**Issue by shootingdarts** [cse110-sp24-group27/cse110-sp24-group27#35]

**Comment by shootingdarts** [comment]
Add more detailed designs to the creation popup pages.

**Comment by hakwok** [comment]
I've completed and finalized all of the designs of the web-app.

Miro: https://miro.com/app/board/uXjVKMhqT8E=/
Figma: https://www.figma.com/files/recents-and-sharing/recently-viewed?fuid=1370233579390992385
