### ISSUE TITLE
Journal Entry Page CSS

### ISSUE THREAD

**Issue by shootingdarts** [cse110-sp24-group27/cse110-sp24-group27#36]
Link to Project Tracker: https://27wayfarers.atlassian.net/browse/KAN-21  

This issue is done when: 

- [x] Entry can be seen fully
- [x] Entry is a box containing/showing a markdown file
- [x] Visuals match figma design

**Comment by shootingdarts** [comment]
Test the visual of the Journal Entry (this page is mostly static so not much to do with JS) and present the visual to @hakwok upon completion.

**Comment by hakwok** [comment]
The criteria has been met
