### ISSUE TITLE
Project Homepage JS

### ISSUE THREAD

**Issue by shootingdarts** [cse110-sp24-group27/cse110-sp24-group27#59]
Wrap up homepage and integrate JS w/ Local Storage.

**Comment by TimothyLam727** [comment]
functionality:
- drop down menu (Home, Setting)
- display profile
- drag project (with localstorage)
- project deletion
- jump to project page by clicking the project name

**Comment by TimothyLam727** [comment]
All functionalities are implemented. Removed the drop and drag functionality
